# Generated by Django 5.1.3 on 2024-12-03 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0013_uploadfile_delete_uploadfileform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadFile',
            new_name='UploadFiles',
        ),
    ]
